swagger: '2.0'
info:
  version: "0.1.0"
  title: MyWeibo API

host: mw.ax003d.info

schemes:
  - http

paths:
  /v1/tagignore:
    post:
      summary: 添加忽略关键字
      security:
        - api_key: []
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            properties:
              tagignore:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: 成功添加忽略关键字

securityDefinitions:
  api_key:
    type: apiKey
    name: X-MyWeibo-API-Key
    in: header